const app = document.querySelector('#app');

const menu = [
  { id:'soe', category:'经典咖啡', name:'耶加雪菲 SOE 美式', desc:'柑橘、红糖、巧克力', price:15, temps:['冷','热'], defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'🍊' },
  { id:'grape', category:'经典咖啡', name:'黑葡萄美式', desc:'葡萄酸感，清爽果香', price:24, temps:['冷','热'], defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'🍇' },
  { id:'salary', category:'经典咖啡', name:'升薪美式', desc:'顺口经典美式', price:20, temps:['冷','热'], defaults:{temp:'热',sugar:'标准'}, accent:'☕' },
  { id:'latte', category:'经典咖啡', name:'拿铁', desc:'浓缩与牛奶', price:22, temps:['冷','热'], milk:true, defaults:{temp:'热',ice:'正常冰',sugar:'标准',milk:'鲜奶'}, accent:'🥛' },
  { id:'coconut-latte', category:'经典咖啡', name:'厚椰拿铁', desc:'椰香浓郁', price:24, temps:['冷','热'], milk:true, defaults:{temp:'冷',ice:'正常冰',sugar:'标准',milk:'厚椰乳'}, accent:'🥥' },
  { id:'dirty', category:'经典咖啡', name:'Dirty', desc:'冰牛奶与热浓缩', price:24, temps:['冷'], milk:true, locked:true, defaults:{temp:'冷',ice:'不加冰',sugar:'不另外加糖',milk:'鲜奶'}, accent:'🤎' },
  { id:'oat-latte', category:'经典咖啡', name:'燕麦拿铁', desc:'燕麦奶基底', price:26, temps:['冷','热'], milk:true, defaults:{temp:'冷',ice:'正常冰',sugar:'标准',milk:'燕麦奶'}, accent:'🌾' },
  { id:'matcha-latte', category:'经典咖啡', name:'抹茶拿铁（含咖）', desc:'抹茶与浓缩咖啡', price:26, temps:['冷','热'], milk:true, defaults:{temp:'冷',ice:'正常冰',sugar:'标准',milk:'鲜奶'}, accent:'🍵' },
  { id:'taro-dirty', category:'创意咖啡', name:'香芋 Dirty', desc:'香芋与咖啡融合', price:24, temps:['冷'], milk:true, locked:true, defaults:{temp:'冷',ice:'不加冰',sugar:'标准',milk:'鲜奶'}, accent:'💜' },
  { id:'salt-mocha', category:'创意咖啡', name:'咸摩卡', desc:'海盐与巧克力', price:24, temps:['冷','热'], milk:true, defaults:{temp:'冷',ice:'正常冰',sugar:'标准',milk:'鲜奶'}, accent:'🍫' },
  { id:'osmanthus', category:'创意咖啡', name:'桂花酒酿拿铁', desc:'桂花与酒酿香气', price:26, temps:['冷','热'], milk:true, defaults:{temp:'热',ice:'正常冰',sugar:'标准',milk:'鲜奶'}, accent:'🌼' },
  { id:'elderberry', category:'创意咖啡', name:'接骨木气泡美式', desc:'清新气泡果香', price:22, temps:['冷'], defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'🫧' },
  { id:'lemon', category:'创意咖啡', name:'柠香冰咖', desc:'柠檬清香', price:20, temps:['冷'], defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'🍋' },
  { id:'green-coconut', category:'创意咖啡', name:'青椰美式', desc:'青椰水与浓缩', price:24, temps:['冷'], defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'🌴' },
  { id:'matcha-milk', category:'无咖啡因', name:'抹茶鲜奶（不含咖啡）', desc:'抹茶与鲜奶', price:30, temps:['冷','热'], milk:true, noCoffee:true, defaults:{temp:'热',ice:'正常冰',sugar:'标准',milk:'鲜奶'}, accent:'🍵' },
  { id:'pomelo', category:'无咖啡因', name:'腌渍柚子樱花茶', desc:'柚子与樱花', price:26, temps:['冷','热'], noCoffee:true, defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'🌸' },
  { id:'peach-tea', category:'无咖啡因', name:'白桃乌龙茶', desc:'白桃与乌龙', price:26, temps:['冷','热'], noCoffee:true, defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'🍑' },
  { id:'brown-rose', category:'无咖啡因', name:'古法黑糖玫瑰茶', desc:'黑糖与玫瑰', price:22, temps:['冷','热'], noCoffee:true, defaults:{temp:'热',ice:'正常冰',sugar:'标准'}, accent:'🌹' },
  { id:'temper-peach', category:'气泡水', name:'脾气水蜜桃', desc:'水蜜桃风味气泡', price:22, temps:['冷'], noCoffee:true, defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'🍑' },
  { id:'passion-plum', category:'气泡水', name:'百香话梅苏打', desc:'百香果与话梅', price:22, temps:['冷'], noCoffee:true, defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'✨' },
  { id:'strawberry', category:'气泡水', name:'草莓苏打', desc:'草莓果香', price:22, temps:['冷'], noCoffee:true, defaults:{temp:'冷',ice:'正常冰',sugar:'标准'}, accent:'🍓' },
  { id:'kiwi', category:'好吃的', name:'奇亚籽可颂', desc:'烘焙点心', price:16, food:true, defaults:{}, accent:'🥐' },
  { id:'choco', category:'好吃的', name:'巧克力双色羊角', desc:'巧克力可颂', price:18, food:true, defaults:{}, accent:'🍫' },
  { id:'bbq', category:'好吃的', name:'叉烧可颂', desc:'咸口可颂', price:16, food:true, defaults:{}, accent:'🥐' },
  { id:'butter', category:'好吃的', name:'招牌黄油可颂', desc:'经典黄油香', price:12, food:true, defaults:{}, accent:'🧈' }
];

const state = {
  screen:'home', communication:'点击卡片', category:'经典咖啡', editing:null, draft:null, cart:[], service:{pickup:'店内享用',urgency:'不着急',note:''}, partnerStep:0, reply:'', serviceIntent:'', serviceReply:'',freeInput:'',inputResult:false, freeInput:'', inputResult:false, feedback:{clear:0,helpful:0,pressure:0,note:''}
};

const esc = (v='') => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const product = id => menu.find(x=>x.id===id);
const money = n => `¥${n}`;
const drinkOptions = {
  ice:['正常冰','少冰','去冰'], sugar:['标准','少糖','不另外加糖'], milk:['鲜奶','燕麦奶 +4','厚椰乳'], shots:['标准浓度','加一份浓缩 +4']
};
function progress(n){return `<div class="progress">${[1,2,3,4].map(i=>`<i class="${i<=n?'active':''}"></i>`).join('')}</div>`}
function itemPrice(item){let p=product(item.id).price;if(item.milk==='燕麦奶 +4')p+=4;if(item.shots==='加一份浓缩 +4')p+=4;return p*item.qty}
function total(){return state.cart.reduce((n,x)=>n+itemPrice(x),0)}
function itemSummary(i){const p=product(i.id);if(p.food)return `${i.qty} 份`;return [i.temp,i.temp==='冷'?i.ice:'',i.sugar,i.milk,i.shots,i.qty>1?`${i.qty} 杯`:''].filter(Boolean).join(' · ')}
function meaningfulChanges(i){const p=product(i.id), d=p.defaults;return [['温度',i.temp,d.temp],['冰量',i.ice,d.ice],['甜度',i.sugar,d.sugar],['奶基底',i.milk,d.milk],['浓度',i.shots,'标准浓度']].filter(x=>x[1]&&x[1]!==x[2])}

function home(){return `<div class="hero"><section class="hero-copy"><div class="eyebrow">ETHER COFFEE × 会意</div><h1>让每一种表达，<br>都被温柔看见。</h1><p class="lead">会意把点单前、制作中和取餐时的沟通，变成顾客与听障咖啡师都看得见、能确认、可回应的信息。</p><div class="access-points"><span>👋 先说明沟通方式</span><span>👀 修改实时可见</span><span>💬 服务中双向回应</span></div><div class="action-row"><button class="primary" data-action="connect">开始一次无障碍服务</button><button class="secondary" data-action="partner-demo">直接看咖啡师端</button></div></section><aside class="hero-art"><div class="bubble one">燕麦奶，加一份浓缩</div><div class="bubble two">少冰修改已看见 👀</div><div class="bubble three">一起确认，再开始制作</div><div class="cup"></div></aside></div>`}


function connect(){const methods=[['点击卡片','👆','不需要说话，点选需求卡'],['语音转文字','🎙️','我说话，系统把内容变成大字'],['直接打字','⌨️','输入文字，直接显示给咖啡师']];return `<div class="page-head"><div><div class="eyebrow">开始前 · 先建立共同语言</div><h2>你好，欢迎来到 Ether Coffee</h2><p class="lead">请选择你最方便的表达方式，之后随时可以切换。</p></div>${progress(1)}</div><section class="deaf-intro"><div class="intro-person"><span>👋</span><div><strong>你好，欢迎来到 Ether Coffee</strong><p>我有听力障碍，但我会看字幕、需求卡和视觉提醒，也可以在屏幕上回应你。</p></div></div><div class="method-grid">${methods.map(m=>`<button class="method ${state.communication===m[0]?'selected':''}" data-communication="${m[0]}"><b>${m[1]}</b><strong>${m[0]}</strong><small>${m[2]}</small></button>`).join('')}</div><div class="communication-tips"><strong>我们可以这样配合：</strong><span>修改订单请在屏幕确认</span><span>需要帮助请点需求卡，不必提高音量</span><span>咖啡师的回应会以大字显示</span></div><button class="step-action" data-action="order">我知道了，开始点单</button></section>`}

function order(){if(state.communication!=='点击卡片')return freeOrder();const cats=[...new Set(menu.map(x=>x.category))];const items=menu.filter(x=>x.category===state.category);return `<div class="page-head"><div><div class="eyebrow">第一步 · 选择商品</div><h2>Ether Coffee 菜单</h2><p class="lead">你正在使用「${state.communication}」。所有修改会变成视觉卡片直达咖啡师，不需要隔空呼喊。</p></div>${progress(2)}</div><div class="access-strip"><span>👀 咖啡师将看到每一项修改</span><button data-action="connect">切换表达方式</button></div><div class="category-tabs">${cats.map(c=>`<button class="${c===state.category?'active':''}" data-category="${c}">${c}</button>`).join('')}</div><div class="menu-grid">${items.map(p=>`<button class="menu-card" data-product="${p.id}"><span class="menu-icon">${p.accent}</span><span class="menu-info"><strong>${p.name}</strong><small>${p.desc}</small><span class="menu-meta">${p.food?'现烤点心':p.temps.join('/')} ${p.noCoffee?' · 无咖啡因':''}</span></span><b>${money(p.price)}</b></button>`).join('')}</div>${cartBar()}`}
function cartBar(){if(!state.cart.length)return '';return `<button class="cart-bar" data-action="cart"><span><b>${state.cart.reduce((n,x)=>n+x.qty,0)}</b> 已选商品</span><strong>${money(total())} · 查看订单</strong></button>`}


function freeOrder(){const voice=state.communication==='语音转文字';return `<div class="page-head"><div><div class="eyebrow">${voice?'语音点单':'文字点单'} · 对话会变成视觉订单</div><h2>${voice?'直接说出你想喝的':'把你的需求打出来'}</h2><p class="lead">例如：我要两杯冰拿铁，少冰少糖，换燕麦奶，其中一杯加浓，打包，我比较赶时间。</p></div>${progress(2)}</div><div class="mode-switch"><button data-action="connect">切换表达方式</button><span>当前方式：${state.communication}</span></div><section class="panel free-order"><div class="conversation-preview"><div class="speaker customer"><small>顾客</small><p>${state.freeInput?esc(state.freeInput):'你的表达会出现在这里，并同步变成咖啡师可见的字幕。'}</p></div><div class="speaker barista"><small>咖啡师看到</small><p>${state.freeInput?esc(state.freeInput):'等待顾客表达……'}</p></div></div>${voice?`<button class="big-mic" data-action="capture-voice">🎙️<strong>${state.freeInput?'重新说一次':'按下开始说话'}</strong><small>演示版点击后模拟识别一条复杂订单</small></button>`:`<label class="field"><strong>输入点单或其他需求</strong><textarea data-free-input placeholder="例如：一杯冰拿铁，少冰，换燕麦奶……">${esc(state.freeInput)}</textarea></label>`}<button class="step-action" data-action="understand" ${state.freeInput?'':'disabled'}>AI 整理为订单，请双方确认</button><div class="example-chips"><span>可以自由表达：</span><button data-example="一杯冰拿铁，少冰少糖，换燕麦奶，加一份浓缩，打包，我想知道等多久">复杂点单</button><button data-example="我想要不含咖啡的热饮，不要太甜">描述偏好</button><button data-example="不好意思，我想把刚才那杯改成少冰">临时改单</button></div></section>`}

function parseFreeOrder(){const t=state.freeInput;let id=t.includes('抹茶')&&t.includes('不含咖啡')?'matcha-milk':t.includes('白桃')?'peach-tea':t.includes('美式')?'soe':'latte';const p=product(id);const item=makeDraft(p);if(p.temps.includes('冷')&&(t.includes('冰')||t.includes('冷')))item.temp='冷';if(t.includes('热')&&p.temps.includes('热'))item.temp='热';if(t.includes('少冰'))item.ice='少冰';else if(t.includes('去冰')||t.includes('不要冰'))item.ice='去冰';if(t.includes('少糖')||t.includes('不要太甜'))item.sugar='少糖';if(t.includes('不加糖'))item.sugar='不另外加糖';if(t.includes('燕麦'))item.milk='燕麦奶 +4';if(t.includes('厚椰'))item.milk='厚椰乳';if(t.includes('加浓')||t.includes('浓缩'))item.shots='加一份浓缩 +4';const m=t.match(/[两二2]杯/);if(m&&t.includes('其中一杯')&&item.shots==='加一份浓缩 +4'){const regular={...item,qty:1,shots:'标准浓度'};const extra={...item,qty:1};state.cart=[regular,extra]}else{if(m)item.qty=2;state.cart=[item]};if(t.includes('打包'))state.service.pickup='打包带走';if(t.includes('赶时间'))state.service.urgency='比较赶时间';else if(t.includes('等多久')||t.includes('等待'))state.service.urgency='想知道等待时间';state.inputResult=true;state.screen='confirm'}

function configure(){const p=product(state.draft.id),d=state.draft;const option=(key,title,arr)=>`<div class="option-group"><h3>${title}</h3><div class="option-row">${arr.map(x=>`<button class="option ${d[key]===x?'selected':''}" data-option="${key}:${x}">${x}</button>`).join('')}</div></div>`;return `<div class="page-head"><div><div class="eyebrow">配置商品</div><h2>${p.accent} ${p.name}</h2><p class="lead">${p.desc} · 基础价 ${money(p.price)}</p></div>${progress(2)}</div><div class="access-strip"><span>每个选择都会以大字和颜色变化显示给咖啡师</span><span>当前：${state.communication}</span></div><section class="panel config-panel">${p.food?'':`${option('temp','温度',p.temps)}${d.temp==='冷'&&p.id!=='dirty'&&p.id!=='taro-dirty'?option('ice','冰量',drinkOptions.ice):''}${option('sugar','甜度',drinkOptions.sugar)}${p.milk?option('milk','奶基底',drinkOptions.milk):''}${!p.noCoffee?option('shots','咖啡浓度',drinkOptions.shots):''}`}<div class="option-group"><h3>数量</h3><div class="quantity"><button data-qty="-1">−</button><strong>${d.qty}</strong><button data-qty="1">＋</button></div></div><label class="field"><strong>这杯的补充需求（选填）</strong><input data-item-note value="${esc(d.note)}" placeholder="例如：分开装、不要吸管" maxlength="40"></label><div class="action-row"><button class="primary" data-action="save-item">${state.editing===null?'加入订单':'保存修改'} · ${money(itemPrice(d))}</button><button class="ghost" data-action="order">返回菜单</button></div></section>`}

function cart(){return `<div class="page-head"><div><div class="eyebrow">第三步 · 确认订单</div><h2>看看有没有遗漏</h2><p class="lead">所有修改都会清楚地显示给咖啡师。</p></div>${progress(3)}</div><div class="access-strip important"><span>🔔 提交后若要改单，请使用「服务需求卡」，咖啡师会收到视觉提醒</span></div><div class="checkout-layout"><section class="panel"><div class="cart-list">${state.cart.map((i,n)=>{const p=product(i.id);return `<div class="cart-item"><div class="menu-icon">${p.accent}</div><div><strong>${p.name}</strong><small>${itemSummary(i)}</small>${i.note?`<small>备注：${esc(i.note)}</small>`:''}</div><b>${money(itemPrice(i))}</b><div class="item-actions"><button data-edit="${n}">修改</button><button data-remove="${n}">删除</button></div></div>`}).join('')}</div><button class="add-more" data-action="order">＋ 继续添加商品</button></section><aside class="panel"><div class="option-group"><h3>取餐方式</h3><div class="option-row">${['店内享用','打包带走'].map(x=>`<button class="option ${state.service.pickup===x?'selected':''}" data-service="pickup:${x}">${x}</button>`).join('')}</div></div><div class="option-group"><h3>时间需求</h3><div class="option-row">${['不着急','想知道等待时间','比较赶时间'].map(x=>`<button class="option ${state.service.urgency===x?'selected':''}" data-service="urgency:${x}">${x}</button>`).join('')}</div></div><label class="field"><strong>整单补充需求（选填）</strong><textarea data-service-note placeholder="例如：其中一杯先做">${esc(state.service.note)}</textarea></label><div class="total"><span>合计</span><strong>${money(total())}</strong></div><button class="step-action" data-action="confirm-order">确认并发给咖啡师</button></aside></div>`}

function confirm(){return `<div class="page-head"><div><div class="eyebrow">顾客确认</div><h2>最终订单是这样，对吗？</h2><p class="lead">确认后咖啡师才开始制作。</p></div>${progress(3)}</div><div class="confirm-protocol"><b>双方确认协议</b><span>① 顾客确认文字</span><span>② 咖啡师确认已看见</span><span>③ 再开始制作</span></div><section class="panel order-card"><div class="order-title"><strong>订单 #018</strong><span class="tag">等待顾客确认</span></div><div class="order-body">${state.cart.map(i=>{const p=product(i.id);return `<div class="confirm-item"><div><strong>${p.name} × ${i.qty}</strong><p>${itemSummary(i)}</p></div><b>${money(itemPrice(i))}</b>${meaningfulChanges(i).length?`<div class="change-list">${meaningfulChanges(i).map(x=>`<span>${x[0]}：<s>${x[2]||'默认'}</s> → <strong>${x[1]}</strong></span>`).join('')}</div>`:''}</div>`}).join('')}<div class="order-line"><span>取餐</span><strong>${state.service.pickup}</strong></div><div class="order-line"><span>时间需求</span><strong>${state.service.urgency}</strong></div>${state.service.note?`<div class="order-line"><span>补充需求</span><strong>${esc(state.service.note)}</strong></div>`:''}<div class="total"><span>合计</span><strong>${money(total())}</strong></div><div class="action-row"><button class="primary" data-action="send-order">确认无误，发给咖啡师</button><button class="ghost" data-action="cart">返回修改</button></div></div></section>`}

function partner(){if(!state.cart.length){state.cart=[{id:'latte',temp:'冷',ice:'少冰',sugar:'少糖',milk:'燕麦奶 +4',shots:'加一份浓缩 +4',qty:2,note:'其中一杯不要吸管'}];state.service={pickup:'打包带走',urgency:'比较赶时间',note:'想知道预计等待时间'}}const allChanges=state.cart.flatMap(i=>meaningfulChanges(i));const steps=['确认订单与修改项',`准备 ${state.cart.reduce((n,x)=>n+x.qty,0)} 件商品`,'向顾客展示预计等待时间','完成后视觉提示取餐'];return `<div class="page-head"><div><div class="eyebrow">咖啡师端 · 新订单 #018</div><h2>${state.cart.length} 种商品，${allChanges.length} 项个性配置</h2><p class="lead">声音已转成视觉任务：新消息闪动提醒、改动前后对比、顾客状态与快速大字回应都在同一屏。</p></div>${progress(4)}</div><div class="partner-layout"><section class="panel"><div class="alert">🔔 新订单 · ${state.service.pickup} · ${state.service.urgency}</div>${state.cart.map(i=>{const p=product(i.id);return `<div class="barista-ticket"><header><strong>${p.accent} ${p.name} × ${i.qty}</strong><b>${money(itemPrice(i))}</b></header><div class="ticket-options">${[i.temp,i.ice,i.sugar,i.milk,i.shots].filter(Boolean).map(x=>`<span>${x}</span>`).join('')}</div>${meaningfulChanges(i).length?`<div class="change-list">${meaningfulChanges(i).map(x=>`<span>${x[0]}：<s>${x[2]||'默认'}</s> → <strong>${x[1]}</strong></span>`).join('')}</div>`:''}${i.note?`<p class="ticket-note">备注：${esc(i.note)}</p>`:''}</div>`}).join('')}<div class="steps">${steps.map((s,i)=>`<div class="step ${i<state.partnerStep?'done':''} ${i===state.partnerStep?'current':''}"><span class="step-num">${i<state.partnerStep?'✓':i+1}</span><strong>${s}</strong></div>`).join('')}</div><button class="step-action" data-action="next-step">${state.partnerStep>=steps.length-1?'订单制作完成':'完成这一步'}</button></section><aside class="panel"><div class="eyebrow">沟通建议</div><h3>${state.service.urgency==='比较赶时间'?'顾客比较赶时间':'向顾客同步进度'}</h3><p class="lead">选择一句话，会以大字展示给顾客。</p><div class="quick-replies">${['订单修改已确认','预计需要 8 分钟','请给我一点时间','我想邀请同事一起帮忙'].map(t=>`<button data-reply="${t}">${state.reply===t?'✓ ':''}${t}</button>`).join('')}</div>${state.reply?`<div class="caption customer-display">${state.reply}</div>`:''}<button class="primary full" data-action="service">进入制作中的双向沟通</button><button class="ghost full" data-action="cart">顾客需要再次改单</button></aside></div>`}


function service(){const intents=[['询问进度','⏱️','还需要等多久？'],['修改订单','✏️','我想修改刚才的订单'],['需要物品','🧻','我需要纸巾 / 吸管 / 水'],['需要帮助','🙋','我想请你帮忙']];return `<div class="page-head"><div><div class="eyebrow">制作中 · 双向沟通</div><h2>不靠呼喊，也不会错过需求</h2><p class="lead">顾客点击需求卡，咖啡师端立即闪动；咖啡师点击回应，顾客端显示大字。</p></div>${progress(4)}</div><div class="live-service"><section class="panel customer-side"><div class="side-label">顾客手机</div><h3>现在需要什么？</h3><div class="intent-grid">${intents.map(x=>`<button class="intent ${state.serviceIntent===x[0]?'selected':''}" data-intent="${x[0]}|${x[2]}"><b>${x[1]}</b><strong>${x[0]}</strong><small>${x[2]}</small></button>`).join('')}</div>${state.serviceReply?`<div class="customer-reply"><small>咖啡师回复</small><strong>${state.serviceReply}</strong><span>✓ 已收到</span></div>`:`<div class="waiting-card">选择后，请看咖啡师是否确认</div>`}</section><section class="panel barista-side"><div class="side-label">咖啡师屏幕</div>${state.serviceIntent?`<div class="visual-alert"><span>🔔</span><div><small>顾客发来新需求</small><strong>${state.serviceIntent}</strong><p>${state.serviceIntentText}</p></div></div><div class="quick-replies">${['已看见，我来处理','预计还需要 5 分钟','请在屏幕上修改订单','我想邀请同事一起帮忙'].map(t=>`<button data-service-reply="${t}">${state.serviceReply===t?'✓ ':''}${t}</button>`).join('')}</div>`:`<div class="quiet-state"><span>👀</span><strong>正在等待顾客需求</strong><p>新消息会以闪动和振动提醒，不依赖听见呼喊。</p></div>`}<div class="pickup-preview"><small>制作完成后的视觉取餐提醒</small><strong>#018 张先生 · 可以取餐</strong><button data-action="pickup">模拟完成制作</button></div></section></div><div class="action-row"><button class="primary" data-action="feedback">结束体验并反馈</button></div>`}

function feedback(){const row=(k,t,a)=>`<div><strong>${t}</strong><div class="feedback-scale">${a.map((x,i)=>`<button class="${state.feedback[k]===i+1?'selected':''}" data-rate="${k}:${i+1}">${x[0]}<small>${x[1]}</small></button>`).join('')}</div></div>`;return `<div class="page-head"><div><div class="eyebrow">和咖啡师一起完善</div><h2>这次点单好用吗？</h2><p class="lead">你的感受决定下一版怎么改。</p></div></div><section class="panel">${row('clear','订单和配置看得清楚吗？',[['😕','不清楚'],['🙂','还可以'],['😊','很清楚']])}${row('helpful','制作步骤有帮助吗？',[['😕','没帮助'],['🙂','有一点'],['😊','很有帮助']])}${row('pressure','使用时感觉轻松吗？',[['😣','更有压力'],['🙂','差不多'],['😊','更轻松']])}<label><strong>最想改变哪一点？</strong><textarea data-note placeholder="例如：字再大一点、选项太多、修改需要更醒目……">${esc(state.feedback.note)}</textarea></label><div class="action-row"><button class="primary" data-action="submit-feedback">提交本次反馈</button><button class="ghost" data-action="partner-demo">返回体验</button></div></section>`}
function thanks(){return `<section class="panel success"><div class="success-icon">✓</div><div class="eyebrow">谢谢你的共同设计</div><h2>让工具适合每一种沟通方式。</h2><p class="lead" style="margin:auto">反馈已保存在当前设备，我们会据此调整菜单、配置和提醒方式。</p><div class="action-row" style="justify-content:center"><button class="primary" data-action="reset">重新体验</button></div></section>`}
function render(){const view={home,connect,order,configure,cart,confirm,partner,service,feedback,thanks}[state.screen];app.innerHTML=view();window.scrollTo({top:0,behavior:'smooth'})}
function makeDraft(p){return {id:p.id,temp:p.defaults.temp||'',ice:p.defaults.ice||'',sugar:p.defaults.sugar||'',milk:p.defaults.milk||'',shots:p.food||p.noCoffee?'':'标准浓度',qty:1,note:''}}

document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;const {action,category,product:pid,option,qty,edit,remove,service,reply,rate,communication,intent}=el.dataset;
 if(el.dataset.example){state.freeInput=el.dataset.example;render();return}
 if(category){state.category=category;render();return} if(pid){state.editing=null;state.draft=makeDraft(product(pid));state.screen='configure';render();return}
 if(option){const [k,v]=option.split(':');state.draft[k]=v;if(k==='temp'&&v==='热')state.draft.ice='';if(k==='temp'&&v==='冷'&&!state.draft.ice)state.draft.ice='正常冰';render();return}
 if(qty){state.draft.qty=Math.max(1,Math.min(9,state.draft.qty+Number(qty)));render();return}
 if(edit!==undefined){state.editing=Number(edit);state.draft={...state.cart[state.editing]};state.screen='configure';render();return}
 if(remove!==undefined){state.cart.splice(Number(remove),1);state.screen=state.cart.length?'cart':'order';render();return}
 if(service){const [k,v]=service.split(':');state.service[k]=v;render();return}
 if(reply){state.reply=reply;navigator.vibrate?.(80);render();return}
 if(rate){const [k,v]=rate.split(':');state.feedback[k]=Number(v);render();return}
 if(communication){state.communication=communication;render();return}
 if(intent){const [name,text]=intent.split('|');state.serviceIntent=name;state.serviceIntentText=text;state.serviceReply='';navigator.vibrate?.([100,60,100]);render();return}
 if(el.dataset.serviceReply){state.serviceReply=el.dataset.serviceReply;navigator.vibrate?.(80);render();return}
 const screens={connect:'connect',order:'order',cart:'cart','confirm-order':'confirm','send-order':'partner','partner-demo':'partner',service:'service',feedback:'feedback',home:'home'};
 if(screens[action]){state.screen=screens[action];render();return}
 if(action==='capture-voice'){state.freeInput='两杯冰拿铁，少冰少糖，换燕麦奶，其中一杯加一份浓缩，打包，我比较赶时间';render();return}
 if(action==='understand'){parseFreeOrder();render();return}
 if(action==='save-item'){if(state.editing===null)state.cart.push({...state.draft});else state.cart[state.editing]={...state.draft};state.editing=null;state.screen='order';render();return}
 if(action==='pickup'){state.serviceReply='订单已完成，请凭 #018 取餐';navigator.vibrate?.([120,80,120]);render();return}
 if(action==='next-step'){if(state.partnerStep<3){state.partnerStep++;navigator.vibrate?.(60);render()}else{state.screen='feedback';render()}return}
 if(action==='submit-feedback'){const r=JSON.parse(localStorage.getItem('wemeet-feedback')||'[]');r.push({...state.feedback,createdAt:new Date().toISOString()});localStorage.setItem('wemeet-feedback',JSON.stringify(r));state.screen='thanks';render();return}
 if(action==='reset'){Object.assign(state,{screen:'home',communication:'点击卡片',category:'经典咖啡',editing:null,draft:null,cart:[],service:{pickup:'店内享用',urgency:'不着急',note:''},partnerStep:0,reply:'',serviceIntent:'',serviceReply:'',freeInput:'',inputResult:false,feedback:{clear:0,helpful:0,pressure:0,note:''}});render()}
});
document.addEventListener('input',e=>{if(e.target.matches('[data-free-input]'))state.freeInput=e.target.value;if(e.target.matches('[data-item-note]'))state.draft.note=e.target.value;if(e.target.matches('[data-service-note]'))state.service.note=e.target.value;if(e.target.matches('[data-note]'))state.feedback.note=e.target.value});
render();
